services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=books'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '53447:5432'
    networks:
      - proovitoo_network
  keycloak_web:
    image: quay.io/keycloak/keycloak:24.0
    container_name: keycloak_web
    environment:
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HOSTNAME: localhost
      KC_HOSTNAME_PORT: 7080
      KC_HEALTH_ENABLED: "true"
      KC_LOG_LEVEL: info
      KC_METRICS_ENABLED: 'true'
    command: ["start-dev", "--http-port", "7080", "--https-port", "7443"]
    ports:
      - '7080:7080'
      - '7443:7443'
    networks:
      - proovitoo_network
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    depends_on:
      - postgres
      - keycloak_web
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/books
      - KEYCLOAK_HOST=keycloak_web
    networks:
      - proovitoo_network
  frontend:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    ports:
      - "4200:4200"
    networks:
      - proovitoo_network
networks:
  proovitoo_network:
    driver: bridge
