spring:
  profiles:
    active: dev
    group:
      dev: dev, dev-keycloak
  application:
    name: smit.proovitoo
  datasource:
    url: jdbc:postgresql://localhost:53447/books
    username: myuser
    password: secret
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.yaml
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:7080/auth/realms/books
          jwk-set-uri: http://localhost:7080/realms/books/protocol/openid-connect/certs

springdoc:
  api-docs.path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui
    oauth:
      client-id: books

logging:
  level:
    org:
      springframework:
        security: DEBUG

